language: java

git:
  depth: false
  quiet: true

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk15
  - openjdk15

services:
  - redis

after_success:
  - bash <(curl -s https://codecov.io/bash)
