language: java
sudo: false

git:
  depth: false
  quiet: true

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk14
  - openjdk14

services:
  - redis-server

env:
  - spring.profiles.active=EXAMPLE
