language: java

git:
  depth: false
  quiet: true

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk14
  - openjdk14

services:
  - redis

env:
  - spring.profiles.active=EXAMPLE

after_success:
  - bash <(curl -s https://codecov.io/bash)
